### ISSUE TITLE
s3 support for data handling

### ISSUE THREAD

**Issue by dstengle** [Netflix/aegisthus#19]
Is it possible to use s3 and elastic mapreduce for processing sstables from backups? Do you push data into hdfs and then process it from -> to there?

**Comment by danielbwatson** [comment]
As of commit https://github.com/Netflix/aegisthus/commit/319b913e201432f86b850cf95af03ab46640665e Aegisthus can now use s3 as an input directory instead of only hdfs input directories.

We don't use this feature in production.  All of our jobs still use the two step process of distcp to hdfs and then running Aegisthus against the uncompressed data on hdfs that Charles mentioned above.
