### ISSUE TITLE
SSTableScanner not able to convert column names correctly.

### ISSUE THREAD

**Issue by tarunsas** [Netflix/aegisthus#30]
Have a schema ,

CREATE TABLE containerdefinition (
  containerdefinitionid text,
  availabilityrules text,
  availabilityruleslockedbyuid text,
  containerdefinitionname text,
  containernamespaceid text,
  createdby text,
  createdtimestamp timestamp,
  deletetime bigint,
  environment text,
  ipaddressallowed list<text>,
  metadata text,
  partner text,
  policymetadata text,
  policymetadatalockedbyuid text,
  properties list<text>,
  swmcomponent text,
  updatedby text,
  updatedtimestamp timestamp,
  PRIMARY KEY (containerdefinitionid)
)

when i set my 
        job.getConfiguration().set("aegisthus.keytype", "UTF8Type");
        job.getConfiguration().set("aegisthus.columntype", "UTF8Type");

Can someone help me with this issue? The same works with if all the columns are "text". If i don't give any column type, it is converting it to BytesType which is very difficult to decrypt.

I am getting error in generating column name.

2014-09-23 18:23:25,079 WARN  [Thread-141] mapred.LocalJobRunner (LocalJobRunner.java:run(560)) - job_local1118817108_0001
java.lang.Exception: org.apache.cassandra.serializers.MarshalException: String didn't validate.
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: org.apache.cassandra.serializers.MarshalException: String didn't validate.
	at org.apache.cassandra.serializers.UTF8Serializer.validate(UTF8Serializer.java:35)
	at org.apache.cassandra.db.marshal.AbstractType.getString(AbstractType.java:154)
	at xx.aegisthus.io.sstable.SSTableScanner.convertColumnName(SSTableScanner.java:333)
	at xx.aegisthus.io.sstable.SSTableScanner.serializeColumns(SSTableScanner.java:272)
	at xx.aegisthus.io.sstable.SSTableScanner.next(SSTableScanner.java:214)
	at xx.aegisthus.input.readers.SSTableRecordReader.nextKeyValue(SSTableRecordReader.java:96)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:533)

**Comment by ggjoshi** [comment]
@danielbwatson Is this functionality for outputting column names and values  correctly in human readable format available? (I am trying to decode a table like below and I do not even see column names or values). If so, in which branch or version of aegisthus?

CREATE TABLE analytics_counters_daily (
  access_attribute varchar,
  matrix_type varchar,
  time_bucket timestamp,
  event_type varchar,
  platform varchar,
  position varchar,
  attribute_key varchar,
  medium varchar,
  count counter,
  PRIMARY KEY ( (access_attribute, matrix_type), time_bucket, event_type, platform, position, attribute_key, medium)
) WITH CLUSTERING ORDER BY (time_bucket DESC);

**Comment by danielbwatson** [comment]
@ggjoshi I did add support for converting the column values in JSON output last year.  As far as I know both column names and column values are being output decoded if the configuration option is set.

Here is the code that gets the column value converter: https://github.com/Netflix/aegisthus/blob/1022c1815f9a0194aeb7a834b11c130a66f24d53/aegisthus-hadoop/src/main/java/com/netflix/aegisthus/output/JsonOutputFormat.java#L81

The problem with this implementation is that it assumes all the column values have the same type and that is frequently an invalid assumption.  It would be nice to let the user specify different converters for different columns.

Another nice feature for tables like yours that are created using CQL would be to automatically determining the types like Daniel Chia did here: https://github.com/Netflix/aegisthus/blob/c7789e1a1092b2588d303ffb41d47eb7bbf9b9b0/aegisthus-hadoop/src/main/java/org/coursera/SSTableExport.java#L68

I use the SSTable output format instead of the JSON output format myself so I don't expect I will be working on these features in the short term.  If you would like to work on them I would be happy to accept a pull request though.

**Comment by ggjoshi** [comment]
thanks @danielbwatson. Couple of questions
1) If you use  SSTable output format instead of the JSON output format, how do you consume output data; is it through PIG or map reduce?
2) If the assumption is that all column types have to be the same, what is the use of CompositeType? Is it for a single column to be of composite type? 
3) In case of counter columns for example; does your tool assume that there will be only one or more columns of the type counter in the table?

**Comment by danielbwatson** [comment]
Well Pig can create map reduce jobs to do the work.   Our normal flow is: 

* Priam backup
* Aegisthus MR job reads the Priam backup and writes out compacted/deduped sstable files.
* Pig MR job reads the Aegisthus output and does whatever cleanup/ETL is needed and writes the cleaned up data to a Hive table
* Downstream jobs consume the Hive table

Sorry I wasn't clear, you can use the CompositeType.  I was just saying the converter that writes out the column value should probably be able to be different for every column.

The code doesn't make any assumptions about counter column types.  The only place that is even referenced in the codebase is in the JsonOutputFormatter where it outputs an extra flag and timestamp if the column is of counter type.
