### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by danchia** [Netflix/aegisthus#48]
There is a test project, but it's not immediately obvious to me how one would run the tests. It would be good if the README documented how to do so.

**Comment by danchia** [comment]
I'm guessing `./gradlew test` does it, but since it doesn't report how many tests were run I'm always a little suspicious.

**Comment by charsmith** [comment]
@danchia That is a good question.  @danielbwatson is on vacation, but hopefully he can pop in and expand on that.

**Comment by danielbwatson** [comment]
I added a section to the README on how to run the tests.  It is `./gradlew test` as you said.

While testing this myself I realized that some Aegisthus tests were written against TestNG and some were written against jUnit.  The way the gradle build was configured it was only running tests for one of these systems and not both.  Additionally since the tests were previously in a separate submodule they were not always failing the build.  I migrated the TestNG tests to jUnit and then moved the Integration (functional?) tests to the aegisthus-hadoop module so they are with the code they are actually testing and will fail the build correctly.
