### ISSUE TITLE
C* 2.1 support

### ISSUE THREAD

**Issue by danchia** [Netflix/aegisthus#49]
@danielbwatson we plan to upgrade to C* 2.1 soon. I was wondering what's the status of C* 2.1 support for aegisthus?

**Comment by danielbwatson** [comment]
I have heard we plan to upgrade soonish as well.  However, as far as I know that hasn't started yet and I don't have any real 2.1 data sets yet.  I did a few tests on some simple data and made a little hack (https://github.com/Netflix/aegisthus/commit/1343de5b389c5a846d8509102078e3ca0680bedf) so that  the current code seems to work with 2.1 and 2.2 sstable input files now.  If you try it out, I would love to know how it works for you.

Once I have some real data I plan to upgrade the Cassandra dependency and make Aegisthus work with their changes.

**Comment by danchia** [comment]
When I was digging in the source code, I thought I noticed some changes to the file format in C* 2.1, but I could be wrong.

I'll try giving it a whirl too. I just don't want to end up duplicating effort with you guys depending on where you are.

**Comment by danielbwatson** [comment]
I'm going to close this for since in my experience this version of Aegisthus does work with C*2.1.   We have a lot of data in C* 2.1 and haven't experienced issues because of file format changes.

**Comment by danchia** [comment]
Sorry, meant to circle back to this. It does work, I had missed out something while testing.
Thanks!
